/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package OrderManagement;

import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import CustomerManagement.Customer;
import CustomerManagement.CustomerManager;

import ProductManagement.Product;
import ProductManagement.ProductManager;
import ProductManagement.ProductStatus;
/**
 *
 * @author Sham
 */
public class NewJFrame extends javax.swing.JFrame {
  private CustomerManager customerManager;
private ProductManager productManager;
private OrderManager orderManager;

private ArrayList<Customer> customers;
private ArrayList<Product> products;
private ArrayList<Product> displayedProducts;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

private void loadCustomers() {

    customerComboBox.removeAllItems();
    customerComboBox.addItem("Select Customer");

    if (customers == null || customers.isEmpty()) {
        return;
    }

    for (Customer customer : customers) {

        if (customer != null) {

            customerComboBox.addItem(
                    customer.getCustomerId()
                    + " - "
                    + customer.getCustomerName()
            );
        }
    }

    customerComboBox.setSelectedIndex(0);
}
private void loadProducts() {

    productComboBox.removeAllItems();

    if (displayedProducts == null) {
        displayedProducts = new ArrayList<>();
    } else {
        displayedProducts.clear();
    }

    productComboBox.addItem("Select Product");

    if (products == null || products.isEmpty()) {
        return;
    }

    for (Product product : products) {

        if (product != null
                && product.getProductStatus()
                == ProductStatus.AVAILABLE
                && product.getQuantity() > 0) {

            displayedProducts.add(product);

            productComboBox.addItem(
                    product.getProductId()
                    + " - "
                    + product.getProductName()
            );
        }
    }

    productComboBox.setSelectedIndex(0);

    jLabelUnitPrice.setText("0.00");
    jLabelTotalAmount.setText("0.00");
}
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
      jTextFieldAddress.setEditable(false);  
      customerManager = new CustomerManager();
    productManager = new ProductManager();
    orderManager = new OrderManager();

    customers = customerManager.getCustomers();
    products = productManager.getProducts();

    displayedProducts = new ArrayList<>();

    loadCustomers();
    loadProducts();
showOrders();
    LocalDate today = LocalDate.now();

    DateTimeFormatter formatter =
            DateTimeFormatter.ofPattern("dd/MM/yyyy");

    OrderDate.setText(
            today.format(formatter)
    );

    setTitle("Order Management");
    setLocationRelativeTo(null);
    setResizable(false);
   
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateOrder = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabeldate = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSelectCustomer = new javax.swing.JLabel();
        customerComboBox = new javax.swing.JComboBox<>();
        lblSelectProduct = new javax.swing.JLabel();
        productComboBox = new javax.swing.JComboBox<>();
        lblQuantityText = new javax.swing.JLabel();
        jTextFieldQuantity = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelUnitPrice = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTotalAmount = new javax.swing.JLabel();
        OrderDate = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmbOrderStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnUpdateStatus = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCreateOrder.setBackground(new java.awt.Color(153, 0, 153));
        btnCreateOrder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCreateOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateOrder.setText("Create Order");
        btnCreateOrder.addActionListener(this::btnCreateOrderActionPerformed);

        btnClear.setBackground(new java.awt.Color(153, 0, 153));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), null, new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 3));

        lblSelectCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSelectCustomer.setText("Select Customer :");

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerComboBox.addActionListener(this::customerComboBoxActionPerformed);

        lblSelectProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSelectProduct.setText("Select Product :");

        productComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productComboBox.addActionListener(this::productComboBoxActionPerformed);

        lblQuantityText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQuantityText.setText("Quantity :");

        jTextFieldQuantity.addActionListener(this::jTextFieldQuantityActionPerformed);
        jTextFieldQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldQuantityKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldQuantityKeyTyped(evt);
            }
        });

        Address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Address.setText("Delivery Address :");

        jTextFieldAddress.addActionListener(this::jTextFieldAddressActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Unit Price :");

        jLabelUnitPrice.setText("0.00");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Total Amount :");

        jLabelTotalAmount.setText("0.00");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Order Date :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSelectCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSelectProduct)
                            .addComponent(lblQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OrderDate, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCustomer)
                    .addComponent(customerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectProduct)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Order Details");

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 3));

        cmbOrderStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PLACED", "CONFIRMED", "PACKED", "READY_FOR_DISPATCH" }));

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        jLabel3.setBackground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Existing Orders");

        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(this::btnUpdateStatusActionPerformed);

        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(this::btnCancelOrderActionPerformed);

        jLabel4.setBackground(new java.awt.Color(153, 0, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 153));
        jLabel4.setText("Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateStatus)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(cmbOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnCancelOrder)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateStatus)
                    .addComponent(btnCancelOrder))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1505, 1505, 1505))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabeldate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboBoxActionPerformed
        // TODO add your handling code here:
           
    int selectedIndex =
            customerComboBox.getSelectedIndex();

    if (selectedIndex <= 0
            || customers == null
            || selectedIndex - 1 >= customers.size()) {

        jTextFieldAddress.setText("");
        return;
    }

    Customer selectedCustomer =
            customers.get(selectedIndex - 1);

    jTextFieldAddress.setText(
            selectedCustomer.getAddress()
    );
    }//GEN-LAST:event_customerComboBoxActionPerformed

    private void jTextFieldQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQuantityActionPerformed
        // TODO add your handling code here:
        calculateTotal();
        jTextFieldAddress.requestFocus();
    }//GEN-LAST:event_jTextFieldQuantityActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
  
    int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to clear the form?",
            "Clear Form",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (choice == JOptionPane.YES_OPTION) {
        clearOrderForm();
    }

   
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
 
     // Validate customer selection
    if (customerComboBox.getSelectedIndex() <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a customer.",
                "Missing Customer",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // Validate product selection
    if (productComboBox.getSelectedIndex() <= 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select a product.",
                "Missing Product",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // Validate quantity field
    String quantityText =
            jTextFieldQuantity.getText().trim();

    if (quantityText.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter the quantity.",
                "Missing Quantity",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int quantity;

    try {

        quantity = Integer.parseInt(quantityText);

        if (quantity <= 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Quantity must be greater than zero.",
                    "Invalid Quantity",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Quantity must be a whole number.",
                "Invalid Quantity",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    // Validate address
    String address =
            jTextFieldAddress.getText().trim();

    if (address.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter the delivery address.",
                "Missing Address",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // Get safe indexes
    int customerIndex =
            customerComboBox.getSelectedIndex() - 1;

    int productIndex =
            productComboBox.getSelectedIndex() - 1;

    // Validate customer index
    if (customers == null
            || customerIndex < 0
            || customerIndex >= customers.size()) {

        JOptionPane.showMessageDialog(
                this,
                "The selected customer is invalid.",
                "Invalid Customer",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    // Validate product index
    if (displayedProducts == null
            || productIndex < 0
            || productIndex >= displayedProducts.size()) {

        JOptionPane.showMessageDialog(
                this,
                "The selected product is invalid.",
                "Invalid Product",
                JOptionPane.ERROR_MESSAGE
        );

        return;
    }

    // Get selected objects
    Customer selectedCustomer =
            customers.get(customerIndex);

    Product selectedProduct =
            displayedProducts.get(productIndex);

    // Check stock before creating order
    if (quantity > selectedProduct.getQuantity()) {

        JOptionPane.showMessageDialog(
                this,
                "Only "
                + selectedProduct.getQuantity()
                + " item(s) are available.",
                "Insufficient Stock",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    // Generate order ID
    String orderId = generateOrderId();

    // Create order through OrderManager
    String result = orderManager.createOrder(
            orderId,
            selectedCustomer,
            selectedProduct,
            quantity,
            address
    );

    // Check result
    if (result.startsWith("Success")) {
double totalAmount =
        selectedProduct.getPrice() * quantity;

String orderSummary =
        "Order created successfully!"
        + "\n\nOrder ID: " + orderId
        + "\nCustomer: "
        + selectedCustomer.getCustomerName()
        + "\nProduct: "
        + selectedProduct.getProductName()
        + "\nQuantity: " + quantity
        + "\nUnit Price: "
        + String.format(
                "%.2f",
                selectedProduct.getPrice()
        )
        + "\nTotal Amount: "
        + String.format(
                "%.2f",
                totalAmount
        )
        + "\nDelivery Address: "
        + address;

JOptionPane.showMessageDialog(
        this,
        orderSummary,
        "Order Created",
        JOptionPane.INFORMATION_MESSAGE
        
        );

        // Reload product data because stock changed
        productManager = new ProductManager();
        products = productManager.getProducts();

       loadProducts();
showOrders();
clearOrderForm();
    } else {

        JOptionPane.showMessageDialog(
                this,
                result,
                "Order Failed",
                JOptionPane.WARNING_MESSAGE
        );
    }
    }//GEN-LAST:event_btnCreateOrderActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
     int selectedIndex =
            productComboBox.getSelectedIndex();

    if (selectedIndex <= 0
            || displayedProducts == null
            || selectedIndex - 1 >= displayedProducts.size()) {

        jLabelUnitPrice.setText("0.00");
        jLabelTotalAmount.setText("0.00");
        return;
    }

    Product selectedProduct =
            displayedProducts.get(selectedIndex - 1);

    jLabelUnitPrice.setText(
            String.format(
                    "%.2f",
                    selectedProduct.getPrice()
            )
    );

    calculateTotal();
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void jTextFieldQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantityKeyReleased
        // TODO add your handling code here:
     
       calculateTotal();
    }//GEN-LAST:event_jTextFieldQuantityKeyReleased

    private void jTextFieldQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldQuantityKeyTyped
        // TODO add your handling code here:
        char character = evt.getKeyChar();

    if (!Character.isDigit(character)) {
        evt.consume();
    }
    }//GEN-LAST:event_jTextFieldQuantityKeyTyped

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit?",
            "Exit",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (choice == JOptionPane.YES_OPTION) {
        dispose();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO add your handling code here:
         int selectedRow =
            tblOrders.getSelectedRow();

    if (selectedRow < 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select an order.",
                "No Order Selected",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String orderId =
            tblOrders.getValueAt(
                    selectedRow,
                    0
            ).toString();

    String selectedStatus =
            cmbOrderStatus
                    .getSelectedItem()
                    .toString();

    OrderStatus newStatus =
            OrderStatus.valueOf(selectedStatus);

    boolean updated =
            orderManager.updateOrderStatus(
                    orderId,
                    newStatus
            );

    if (updated) {

        JOptionPane.showMessageDialog(
                this,
                "Order status updated successfully.",
                "Status Updated",
                JOptionPane.INFORMATION_MESSAGE
        );

        showOrders();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "The order status could not be updated.",
                "Update Failed",
                JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnUpdateStatusActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        // TODO add your handling code here:
      int selectedRow =
            tblOrders.getSelectedRow();

    if (selectedRow < 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please select an order to cancel.",
                "No Order Selected",
                JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String orderId =
            tblOrders.getValueAt(
                    selectedRow,
                    0
            ).toString();

    int choice =
            JOptionPane.showConfirmDialog(
                    this,
                    "Are you sure you want to cancel order "
                    + orderId + "?",
                    "Cancel Order",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
            );

    if (choice != JOptionPane.YES_OPTION) {
        return;
    }

    String result =
            orderManager.cancelOrder(orderId);

    if (result.startsWith("Success")) {

        JOptionPane.showMessageDialog(
                this,
                result,
                "Order Cancelled",
                JOptionPane.INFORMATION_MESSAGE
        );

        productManager = new ProductManager();
        products = productManager.getProducts();

        loadProducts();
        showOrders();

    } else {

        JOptionPane.showMessageDialog(
                this,
                result,
                "Cancellation Failed",
                JOptionPane.WARNING_MESSAGE
        );
    }  
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblOrders.getSelectedRow();

    if (selectedRow >= 0) {

        cmbOrderStatus.setSelectedItem(
                tblOrders.getValueAt(selectedRow, 7).toString()
        );
    } 
    }//GEN-LAST:event_tblOrdersMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel OrderDate;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JComboBox<String> cmbOrderStatus;
    private javax.swing.JComboBox<String> customerComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTotalAmount;
    private javax.swing.JLabel jLabelUnitPrice;
    private javax.swing.JLabel jLabeldate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldQuantity;
    private javax.swing.JLabel lblQuantityText;
    private javax.swing.JLabel lblSelectCustomer;
    private javax.swing.JLabel lblSelectProduct;
    private javax.swing.JComboBox<String> productComboBox;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
private String generateOrderId() {

    int highestNumber = 0;

    for (Order order : orderManager.getOrders()) {

        if (order == null
                || order.getOrderId() == null) {
            continue;
        }

        String orderId =
                order.getOrderId().trim();

        if (orderId.startsWith("ORD")) {

            try {

                int number =
                        Integer.parseInt(
                                orderId.substring(3)
                        );

                if (number > highestNumber) {
                    highestNumber = number;
                }

            } catch (NumberFormatException e) {
                // Ignore invalid order IDs
            }
        }
    }

    return String.format(
            "ORD%04d",
            highestNumber + 1
    );
}


private void calculateTotal() {

    int selectedIndex =
            productComboBox.getSelectedIndex();

    if (selectedIndex <= 0
            || displayedProducts == null) {

        jLabelTotalAmount.setText("0.00");
        return;
    }

    int productIndex = selectedIndex - 1;

    if (productIndex < 0
            || productIndex >= displayedProducts.size()) {

        jLabelTotalAmount.setText("0.00");
        return;
    }

    String quantityText =
            jTextFieldQuantity.getText().trim();

    if (quantityText.isEmpty()) {

        jLabelTotalAmount.setText("0.00");
        return;
    }

    try {

        int quantity =
                Integer.parseInt(quantityText);

        if (quantity <= 0) {

            jLabelTotalAmount.setText("0.00");
            return;
        }

        Product selectedProduct =
                displayedProducts.get(productIndex);

        double total =
                selectedProduct.getPrice() * quantity;

        jLabelTotalAmount.setText(
                String.format("%.2f", total)
        );

    } catch (NumberFormatException e) {

        jLabelTotalAmount.setText("0.00");
    }
}
private void clearOrderForm() {

    if (customerComboBox.getItemCount() > 0) {
        customerComboBox.setSelectedIndex(0);
    }

    if (productComboBox.getItemCount() > 0) {
        productComboBox.setSelectedIndex(0);
    }

    jTextFieldQuantity.setText("");
    jTextFieldAddress.setText("");

    jLabelUnitPrice.setText("0.00");
    jLabelTotalAmount.setText("0.00");

    customerComboBox.requestFocus();
    tblOrders.clearSelection();

cmbOrderStatus.setSelectedIndex(0);
}
private void showOrders() {

    String[] columns = {
        "Order ID",
        "Customer",
        "Product",
        "Quantity",
        "Total",
        "Date",
        "Address",
        "Status"
    };

    ArrayList<Order> orders =
            orderManager.getOrders();
if (orders.isEmpty()) {

    DefaultTableModel model =
            new DefaultTableModel(
                    new Object[0][8],
                    columns
            );

    tblOrders.setModel(model);

    return;
}
    Object[][] data =
            new Object[orders.size()][8];

    for (int i = 0; i < orders.size(); i++) {

        Order order = orders.get(i);

        data[i][0] = order.getOrderId();
        data[i][1] = order.getCustomerName();
        data[i][2] = order.getProductName();
        data[i][3] = order.getQuantity();
        data[i][4] =
                String.format("%.2f", order.getTotal());
        data[i][5] = order.getOrderDate();
        data[i][6] = order.getDeliveryAddress();
        data[i][7] = order.getStatus();
    }

    DefaultTableModel model =
            new DefaultTableModel(data, columns) {

        @Override
        public boolean isCellEditable(
                int row,
                int column) {

            return false;
        }
    };

    tblOrders.setModel(model);
    tblOrders.getTableHeader()
        .setReorderingAllowed(false);

tblOrders.setSelectionMode(
        javax.swing.ListSelectionModel.SINGLE_SELECTION);
if (tblOrders.getRowCount() > 0) {

    tblOrders.setRowSelectionInterval(0, 0);

    cmbOrderStatus.setSelectedItem(
            tblOrders.getValueAt(0, 7).toString()
    );
}
}

    void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
