/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DispatchManagement;
import javax.swing.JOptionPane;


/**
 *
 * @author shahad
 */

public class DeliveryManagementGUI extends javax.swing.JFrame {
    
    private DeliveryManager deliveryManager;
    private DeliveryFileHandler deliveryFileHandler;
    private DeliveryPersonManager deliveryPersonManager;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeliveryManagementGUI.class.getName());

    /**
     * Creates new form DeliveryManagmentGUI
     */
    public DeliveryManagementGUI() {
        initComponents();
        deliveryManager=new DeliveryManager();
        deliveryFileHandler=new DeliveryFileHandler();
        deliveryPersonManager=new DeliveryPersonManager();
        loadDeliveryPersons();
        txtOrderId.setEditable(false);
        txtPhone.setEditable(false);
        txtVehicle.setEditable(false);
        cmbStatus.removeAllItems();
        for (DeliveryStatus status : DeliveryStatus.values()) {
        cmbStatus.addItem(status.toString());
        }

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDeliveryId = new javax.swing.JTextField();
        txtOrderId = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtVehicle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDispatchDate = new javax.swing.JTextField();
        txtExpectedDate = new javax.swing.JTextField();
        txtActualDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        cmbStatus = new javax.swing.JComboBox<>();
        cmbDeliveryPerson = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cmbSearchType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDeliveries = new javax.swing.JTable();
        btnLoad = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel2.setText("Delivery ID:");

        jLabel3.setText("Order ID:");

        jLabel4.setText("Delivery Person:");

        jLabel5.setText("Phone:");

        jLabel6.setText("Vehicle Number:");

        txtDeliveryId.addActionListener(this::txtDeliveryIdActionPerformed);

        txtOrderId.addActionListener(this::txtOrderIdActionPerformed);

        jLabel7.setText("Expected Delivery Date:");

        jLabel8.setText("Dispatch Date:");

        jLabel9.setText("Actual Delivery Date:");

        jLabel10.setText("Delivery Status:");

        jLabel11.setText("Remarks:");

        txtDispatchDate.addActionListener(this::txtDispatchDateActionPerformed);

        txtExpectedDate.addActionListener(this::txtExpectedDateActionPerformed);

        txtRemarks.setColumns(20);
        txtRemarks.setRows(5);
        jScrollPane2.setViewportView(txtRemarks);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStatus.addActionListener(this::cmbStatusActionPerformed);

        cmbDeliveryPerson.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDeliveryPerson.addActionListener(this::cmbDeliveryPersonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeliveryId, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(txtOrderId))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDispatchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtActualDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpectedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtVehicle)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmbDeliveryPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeliveryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtDispatchDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtExpectedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtActualDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDeliveryPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 51, 255))); // NOI18N

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        jLabel12.setText("Search by:");

        jLabel13.setText("Search text:");

        cmbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery ID", "Order ID", "Delivery Person", "Delivery Status" }));
        cmbSearchType.addActionListener(this::cmbSearchTypeActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnSearch))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery List:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 51, 255))); // NOI18N

        tblDeliveries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Delivery ID", "Order ID", "Person", "Phone", "Vehicle", "Dispatch Date", "Expected Date", "Actual Date", "Status", "Remarks"
            }
        ));
        tblDeliveries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeliveriesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDeliveries);

        btnLoad.setText("Load");
        btnLoad.addActionListener(this::btnLoadActionPerformed);

        btnDelete.setText("Delete");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(btnLoad)
                .addGap(84, 84, 84)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoad)
                    .addComponent(btnDelete))
                .addContainerGap(384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addComponent(btnAdd)
                                .addGap(58, 58, 58)
                                .addComponent(btnUpdate)
                                .addGap(35, 35, 35)
                                .addComponent(btnSave)
                                .addGap(47, 47, 47)
                                .addComponent(btnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(385, 385, 385)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtDeliveryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryIdActionPerformed

    private void txtExpectedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpectedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpectedDateActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
String personName = cmbDeliveryPerson.getSelectedItem().toString();

DeliveryPerson selectedPerson =
        deliveryPersonManager.findByName(personName);

if (selectedPerson == null) {
    JOptionPane.showMessageDialog(this,
            "Please select a registered delivery person.");
    return;
}


Delivery delivery = new Delivery(
        txtDeliveryId.getText().trim(),
        txtOrderId.getText().trim(),
        selectedPerson.getPersonName(),
        selectedPerson.getPhone(),
        selectedPerson.getVehicle(),
        txtDispatchDate.getText().trim(),
        txtExpectedDate.getText().trim(),
        txtActualDate.getText().trim(),
        DeliveryStatus.valueOf(cmbStatus.getSelectedItem().toString()),
        txtRemarks.getText().trim()
);
                    
                    
            

    boolean updated = deliveryManager.updateDelivery(
            txtDeliveryId.getText(), delivery);

    if (updated) {

    deliveryFileHandler.saveDeliveries(
            deliveryManager.getAllDeliveries());

    int row = tblDeliveries.getSelectedRow();

    if (row >= 0) {
        tblDeliveries.setValueAt(delivery.getDeliveryId(), row, 0);
        tblDeliveries.setValueAt(delivery.getOrderId(), row, 1);
        tblDeliveries.setValueAt(delivery.getDeliveryPersonName(), row, 2);
        tblDeliveries.setValueAt(delivery.getDeliveryPersonPhone(), row, 3);
        tblDeliveries.setValueAt(delivery.getVehicleNumber(), row, 4);
        tblDeliveries.setValueAt(delivery.getDispatchDate(), row, 5);
        tblDeliveries.setValueAt(delivery.getExpectedDeliveryDate(), row, 6);
        tblDeliveries.setValueAt(delivery.getActualDeliveryDate(), row, 7);
        tblDeliveries.setValueAt(delivery.getDeliveryStatus(), row, 8);
        tblDeliveries.setValueAt(delivery.getRemarks(), row, 9);
    }

    JOptionPane.showMessageDialog(
            this,
            "Delivery updated successfully.");

} else {

    JOptionPane.showMessageDialog(
            this,
            "Unable to update delivery.\n" +
"Please check the information entered.");}
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        deliveryFileHandler.saveDeliveries(
            deliveryManager.getAllDeliveries());

    JOptionPane.showMessageDialog(this,
            "Deliveries saved successfully.");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtDeliveryId.setText("");
        txtOrderId.setText("");
        if(cmbDeliveryPerson.getItemCount()>0){
             cmbDeliveryPerson.setSelectedIndex(0);
                }
        
        txtPhone.setText("");
        txtVehicle.setText("");
        txtDispatchDate.setText("");
        txtExpectedDate.setText("");
        txtActualDate.setText("");
        txtRemarks.setText("");
        
        if(cmbStatus.getItemCount()>0){
            cmbStatus.setSelectedIndex(0);
        }
        tblDeliveries.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         if(cmbDeliveryPerson.getSelectedItem()==null){
       javax.swing.JOptionPane.showMessageDialog(this, "Please select a registered delivery person.");
       return;
   }
         String personName=cmbDeliveryPerson.getSelectedItem().toString();
   DeliveryPerson selectedPerson=deliveryPersonManager.findByName(personName);
   

   Delivery delivery=new Delivery(
   txtDeliveryId.getText().trim(),
   txtOrderId.getText().trim(),
   selectedPerson.getPersonName().trim(),
   selectedPerson.getPhone().trim(),        
   selectedPerson.getVehicle().trim(),
   txtDispatchDate.getText().trim(),
   txtExpectedDate.getText().trim(),       
   txtActualDate.getText().trim(),
   DeliveryStatus.valueOf(cmbStatus.getSelectedItem().toString()),
   txtRemarks.getText().trim()
   );
        

    boolean added = deliveryManager.addDelivery(delivery);
    if (added) {

    deliveryFileHandler.saveDeliveries(
            deliveryManager.getAllDeliveries());

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
            tblDeliveries.getModel();

    model.addRow(new Object[]{
        delivery.getDeliveryId(),
        delivery.getOrderId(),
        delivery.getDeliveryPersonName(),
        delivery.getDeliveryPersonPhone(),
        delivery.getVehicleNumber(),
        delivery.getDispatchDate(),
        delivery.getExpectedDeliveryDate(),
        delivery.getActualDeliveryDate(),
        delivery.getDeliveryStatus(),
        delivery.getRemarks()
    });

    JOptionPane.showMessageDialog(this,
            "Delivery added successfully.");

} else {

    JOptionPane.showMessageDialog(this,
            "Invalid delivery information or duplicate Delivery ID / Order ID.");
}

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtDispatchDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDispatchDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispatchDateActionPerformed

     public void setOrderId(String orderId){
                txtOrderId.setText(orderId);
        }
    private void loadDeliveryPersons(){
        cmbDeliveryPerson.removeAllItems();
        for(DeliveryPerson person : deliveryPersonManager.getDeliveryPersons()){
            cmbDeliveryPerson.addItem(person.getPersonName());
        }
    }

    private void cmbDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeliveryPersonActionPerformed
        // TODO add your handling code here:
       
        if(cmbDeliveryPerson.getSelectedItem()==null){
            return;}
         String personName=cmbDeliveryPerson.getSelectedItem().toString();
        DeliveryPerson person=deliveryPersonManager.findByName(personName);
        if(person!=null){
            txtPhone.setText(person.getPhone());
            txtVehicle.setText(person.getVehicle());
        }
    }//GEN-LAST:event_cmbDeliveryPersonActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        String searchType = cmbSearchType.getSelectedItem().toString();
        String searchText = txtSearch.getText().trim();

        javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) tblDeliveries.getModel();

        model.setRowCount(0);

        boolean found = false;

        for (Delivery delivery : deliveryManager.getAllDeliveries()) {

            boolean match = false;

            switch (searchType) {

                case "Delivery ID":
                match = delivery.getDeliveryId().equalsIgnoreCase(searchText);
                break;

                case "Order ID":
                match = delivery.getOrderId().equalsIgnoreCase(searchText);
                break;

                case "Delivery Person":
                match = delivery.getDeliveryPersonName().equalsIgnoreCase(searchText);
                break;

                case "Delivery Status":
                match = delivery.getDeliveryStatus().toString().equalsIgnoreCase(searchText);
                break;
            }

            if (match) {

                found = true;

                model.addRow(new Object[]{
                    delivery.getDeliveryId(),
                    delivery.getOrderId(),
                    delivery.getDeliveryPersonName(),
                    delivery.getDeliveryPersonPhone(),
                    delivery.getVehicleNumber(),
                    delivery.getDispatchDate(),
                    delivery.getExpectedDeliveryDate(),
                    delivery.getActualDeliveryDate(),
                    delivery.getDeliveryStatus(),
                    delivery.getRemarks()
                });
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this, "No matching delivery found.");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cmbSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchTypeActionPerformed

    private void tblDeliveriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeliveriesMouseClicked
        // TODO add your handling code here:

        int row = tblDeliveries.getSelectedRow();

        if (row >= 0) {

            txtDeliveryId.setText(
                tblDeliveries.getValueAt(row, 0).toString()
            );

            txtOrderId.setText(
                tblDeliveries.getValueAt(row, 1).toString()
            );

            cmbDeliveryPerson.setSelectedItem(
                tblDeliveries.getValueAt(row, 2).toString()
            );

            txtPhone.setText(
                tblDeliveries.getValueAt(row, 3).toString()
            );

            txtVehicle.setText(
                tblDeliveries.getValueAt(row, 4).toString()
            );

            txtDispatchDate.setText(
                tblDeliveries.getValueAt(row, 5).toString()
            );

            txtExpectedDate.setText(
                tblDeliveries.getValueAt(row, 6).toString()
            );

            txtActualDate.setText(
                tblDeliveries.getValueAt(row, 7).toString()
            );

            cmbStatus.setSelectedItem(
                tblDeliveries.getValueAt(row, 8).toString()
            );

            txtRemarks.setText(
                tblDeliveries.getValueAt(row, 9).toString()
            );
        }
    }//GEN-LAST:event_tblDeliveriesMouseClicked

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:

        deliveryManager.setDeliveryList(
            deliveryFileHandler.loadDeliveries());

        javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel)
        tblDeliveries.getModel();

        model.setRowCount(0);

        for (Delivery delivery :
            deliveryManager.getAllDeliveries()) {

            model.addRow(new Object[]{
                delivery.getDeliveryId(),
                delivery.getOrderId(),
                delivery.getDeliveryPersonName(),
                delivery.getDeliveryPersonPhone(),
                delivery.getVehicleNumber(),
                delivery.getDispatchDate(),
                delivery.getExpectedDeliveryDate(),
                delivery.getActualDeliveryDate(),
                delivery.getDeliveryStatus(),
                delivery.getRemarks()
            });

            JOptionPane.showMessageDialog(
                this,
                "Deliveries loaded successfully.");
        }
       
    }//GEN-LAST:event_btnLoadActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeliveryManagementGUI().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbDeliveryPerson;
    private javax.swing.JComboBox<String> cmbSearchType;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblDeliveries;
    private javax.swing.JTextField txtActualDate;
    private javax.swing.JTextField txtDeliveryId;
    private javax.swing.JTextField txtDispatchDate;
    private javax.swing.JTextField txtExpectedDate;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextArea txtRemarks;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtVehicle;
    // End of variables declaration//GEN-END:variables
}