/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DispatchManagement;
import javax.swing.JOptionPane;
/**
 *
 * @author shahad
 */
public class DeliveryDashboardGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeliveryDashboardGUI.class.getName());

    /**
     * Creates new form DeliveryDashboardGUI
     */
    public DeliveryDashboardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPendingDeliveries = new javax.swing.JButton();
        btnDeliveryAssignment = new javax.swing.JButton();
        btnDeliveryReports = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Delivery & Dispatch Management");

        btnPendingDeliveries.setText("Pending Orders");
        btnPendingDeliveries.addActionListener(this::btnPendingDeliveriesActionPerformed);

        btnDeliveryAssignment.setText("Delivery Management");
        btnDeliveryAssignment.addActionListener(this::btnDeliveryAssignmentActionPerformed);

        btnDeliveryReports.setText("Delivery Reports");
        btnDeliveryReports.addActionListener(this::btnDeliveryReportsActionPerformed);

        btnRegister.setText("Register Delivery Person");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 99, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(btnDeliveryReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPendingDeliveries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeliveryAssignment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnRegister)
                .addGap(35, 35, 35)
                .addComponent(btnPendingDeliveries)
                .addGap(35, 35, 35)
                .addComponent(btnDeliveryAssignment)
                .addGap(41, 41, 41)
                .addComponent(btnDeliveryReports)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPendingDeliveriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingDeliveriesActionPerformed
        // TODO add your handling code here:
        new PendingDeliveriesGUI().setVisible(true);
    }//GEN-LAST:event_btnPendingDeliveriesActionPerformed

    private void btnDeliveryAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryAssignmentActionPerformed
        // TODO add your handling code here:
         new DeliveryManagementGUI().setVisible(true);
    }//GEN-LAST:event_btnDeliveryAssignmentActionPerformed

    private void btnDeliveryReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryReportsActionPerformed
        // TODO add your handling code here:
        new DeliveryReportsGUI().setVisible(true);
    }//GEN-LAST:event_btnDeliveryReportsActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        new DeliveryPersonGUI().setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeliveryDashboardGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeliveryAssignment;
    private javax.swing.JButton btnDeliveryReports;
    private javax.swing.JButton btnPendingDeliveries;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
