/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DispatchManagement;
import javax.swing.JOptionPane;
import OrderManagement.Order;
import OrderManagement.OrderManager;
import OrderManagement.OrderStatus;

/**
 *
 * @author shahad
 */

public class DeliveryManagementGUI extends javax.swing.JFrame {
    
    private DeliveryManager deliveryManager;
    private DeliveryFileHandler deliveryFileHandler;
    private OrderManager orderManager;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeliveryManagementGUI.class.getName());

    /**
     * Creates new form DeliveryManagmentGUI
     */
    public DeliveryManagementGUI() {
        initComponents();
        deliveryManager=new DeliveryManager();
        deliveryFileHandler=new DeliveryFileHandler();
        orderManager=new OrderManager();
        cmbStatus.removeAllItems();
        for (DeliveryStatus status : DeliveryStatus.values()) {
        cmbStatus.addItem(status.toString());
        }
        loadPendingOrders();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDeliveryId = new javax.swing.JTextField();
        txtOrderId = new javax.swing.JTextField();
        txtPersonName = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtVehicle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDispatchDate = new javax.swing.JTextField();
        txtExpectedDate = new javax.swing.JTextField();
        txtActualDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        cmbStatus = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDeliveries = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbSearchType = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblPendingOrders = new javax.swing.JTable();
        btnSelectOrder = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblAssigned = new javax.swing.JLabel();
        lblDispatched = new javax.swing.JLabel();
        lblInTransit = new javax.swing.JLabel();
        lblDelivered = new javax.swing.JLabel();
        lblFailed = new javax.swing.JLabel();
        lblReturned = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel1.setText("DELIVERY AND DISPATCH MANAGEMENT ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery Information:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel2.setText("Delivery ID:");

        jLabel3.setText("Order ID:");

        jLabel4.setText("Delivery Person:");

        jLabel5.setText("Phone:");

        jLabel6.setText("Vehicle Number:");

        txtDeliveryId.addActionListener(this::txtDeliveryIdActionPerformed);

        txtOrderId.addActionListener(this::txtOrderIdActionPerformed);

        jLabel7.setText("Expected Delivery Date:");

        jLabel8.setText("Dispatch Date:");

        jLabel9.setText("Actual Delivery Date:");

        jLabel10.setText("Delivery Status:");

        jLabel11.setText("Remarks:");

        txtDispatchDate.addActionListener(this::txtDispatchDateActionPerformed);

        txtExpectedDate.addActionListener(this::txtExpectedDateActionPerformed);

        txtRemarks.setColumns(20);
        txtRemarks.setRows(5);
        jScrollPane2.setViewportView(txtRemarks);

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStatus.addActionListener(this::cmbStatusActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeliveryId, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(txtOrderId))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDispatchDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtActualDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpectedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtPersonName, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtPhone))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVehicle)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeliveryId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtDispatchDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtExpectedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtActualDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnLoad.setText("Load");
        btnLoad.addActionListener(this::btnLoadActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery List:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 51, 255))); // NOI18N

        tblDeliveries.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Delivery ID", "Order ID", "Person", "Phone", "Vehicle", "Dispatch Date", "Expected Date", "Actual Date", "Status", "Remarks"
            }
        ));
        tblDeliveries.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeliveriesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDeliveries);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 51, 255))); // NOI18N

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        jLabel12.setText("Search by:");

        jLabel13.setText("Search text:");

        cmbSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery ID", "Order ID", "Delivery Person", "Delivery Status" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnSearch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery Assignment Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel21.setText("Orders Ready for Dispatch");

        tblPendingOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order ID", "Customer Name", "Delivey Address", "Order Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblPendingOrders);

        btnSelectOrder.setText("Select Order");
        btnSelectOrder.addActionListener(this::btnSelectOrderActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(381, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnSelectOrder)
                                .addGap(223, 223, 223))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelectOrder)
                .addGap(30, 30, 30))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delivery Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(51, 51, 255))); // NOI18N

        jLabel14.setText("Total Deliveries:");

        jLabel15.setText("Assigned:");

        jLabel16.setText("Dispatched:");

        jLabel17.setText("In Transit:");

        jLabel18.setText("Delivered:");

        jLabel19.setText("Failed:");

        jLabel20.setText("Returned:");

        lblTotal.setText("0");

        lblAssigned.setText("0");

        lblDispatched.setText("0");

        lblInTransit.setText("0");

        lblDelivered.setText("0");

        lblFailed.setText("0");

        lblReturned.setText("0");

        btnReport.setText("Generate Report");
        btnReport.addActionListener(this::btnReportActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnReport))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblReturned)
                            .addComponent(lblFailed)
                            .addComponent(lblDelivered)
                            .addComponent(lblInTransit)
                            .addComponent(lblDispatched)
                            .addComponent(lblAssigned)
                            .addComponent(lblTotal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblAssigned))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblDispatched))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblInTransit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblDelivered))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblFailed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblReturned))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnLoad)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAdd)
                                    .addComponent(btnUpdate)
                                    .addComponent(btnDelete)
                                    .addComponent(btnSave)
                                    .addComponent(btnLoad)
                                    .addComponent(btnClear))
                                .addGap(52, 52, 52))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtDeliveryIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryIdActionPerformed

    private void txtExpectedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpectedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpectedDateActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

    String searchType = cmbSearchType.getSelectedItem().toString();
    String searchText = txtSearch.getText().trim();

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblDeliveries.getModel();

    model.setRowCount(0);

    boolean found = false;

    for (Delivery delivery : deliveryManager.getAllDeliveries()) {

        boolean match = false;

        switch (searchType) {

            case "Delivery ID":
                match = delivery.getDeliveryId().equalsIgnoreCase(searchText);
                break;

            case "Order ID":
                match = delivery.getOrderId().equalsIgnoreCase(searchText);
                break;

            case "Delivery Person":
                match = delivery.getDeliveryPersonName().equalsIgnoreCase(searchText);
                break;

            case "Delivery Status":
                match = delivery.getDeliveryStatus().toString().equalsIgnoreCase(searchText);
                break;
        }

        if (match) {

            found = true;

            model.addRow(new Object[]{
                delivery.getDeliveryId(),
                delivery.getOrderId(),
                delivery.getDeliveryPersonName(),
                delivery.getDeliveryPersonPhone(),
                delivery.getVehicleNumber(),
                delivery.getDispatchDate(),
                delivery.getExpectedDeliveryDate(),
                delivery.getActualDeliveryDate(),
                delivery.getDeliveryStatus(),
                delivery.getRemarks()
            });
        }
    }

    if (!found) {
        JOptionPane.showMessageDialog(this, "No matching delivery found.");
    }
   
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Delivery delivery = new Delivery(
            txtDeliveryId.getText(),
            txtOrderId.getText(),
            txtPersonName.getText(),
            txtPhone.getText(),
            txtVehicle.getText(),
            txtDispatchDate.getText(),
            txtExpectedDate.getText(),
            txtActualDate.getText(),
            DeliveryStatus.valueOf(cmbStatus.getSelectedItem().toString()),
                txtRemarks.getText());
            

    boolean updated = deliveryManager.updateDelivery(
            txtDeliveryId.getText(), delivery);

    if (updated) {

    deliveryFileHandler.saveDeliveries(
            deliveryManager.getAllDeliveries());

    int row = tblDeliveries.getSelectedRow();

    if (row >= 0) {
        tblDeliveries.setValueAt(delivery.getDeliveryId(), row, 0);
        tblDeliveries.setValueAt(delivery.getOrderId(), row, 1);
        tblDeliveries.setValueAt(delivery.getDeliveryPersonName(), row, 2);
        tblDeliveries.setValueAt(delivery.getDeliveryPersonPhone(), row, 3);
        tblDeliveries.setValueAt(delivery.getVehicleNumber(), row, 4);
        tblDeliveries.setValueAt(delivery.getDispatchDate(), row, 5);
        tblDeliveries.setValueAt(delivery.getExpectedDeliveryDate(), row, 6);
        tblDeliveries.setValueAt(delivery.getActualDeliveryDate(), row, 7);
        tblDeliveries.setValueAt(delivery.getDeliveryStatus(), row, 8);
        tblDeliveries.setValueAt(delivery.getRemarks(), row, 9);
    }

    JOptionPane.showMessageDialog(
            this,
            "Delivery updated successfully.");

} else {

    JOptionPane.showMessageDialog(
            this,
            "Unable to update delivery.\n" +
"Please check the information entered.");}
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        deliveryFileHandler.saveDeliveries(
            deliveryManager.getAllDeliveries());

    JOptionPane.showMessageDialog(this,
            "Deliveries saved successfully.");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtDeliveryId.setText("");
        txtOrderId.setText("");
        txtPersonName.setText("");
        txtPhone.setText("");
        txtVehicle.setText("");
        txtDispatchDate.setText("");
        txtExpectedDate.setText("");
         txtActualDate.setText("");
    txtRemarks.setText("");

    cmbStatus.setSelectedIndex(0);
    tblDeliveries.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Delivery delivery = new Delivery(
            txtDeliveryId.getText(),
            txtOrderId.getText(),
            txtPersonName.getText(),
            txtPhone.getText(),
            txtVehicle.getText(),
            txtDispatchDate.getText(),
            txtExpectedDate.getText(),
            txtActualDate.getText(),
            DeliveryStatus.valueOf(cmbStatus.getSelectedItem().toString()),
                txtRemarks.getText());

    boolean added = deliveryManager.addDelivery(delivery);
    if (added) {

    deliveryFileHandler.saveDeliveries(
            deliveryManager.getAllDeliveries());

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
            tblDeliveries.getModel();

    model.addRow(new Object[]{
        delivery.getDeliveryId(),
        delivery.getOrderId(),
        delivery.getDeliveryPersonName(),
        delivery.getDeliveryPersonPhone(),
        delivery.getVehicleNumber(),
        delivery.getDispatchDate(),
        delivery.getExpectedDeliveryDate(),
        delivery.getActualDeliveryDate(),
        delivery.getDeliveryStatus(),
        delivery.getRemarks()
    });

    JOptionPane.showMessageDialog(this,
            "Delivery added successfully.");

} else {

    JOptionPane.showMessageDialog(this,
            "Invalid delivery information or duplicate Delivery ID / Order ID.");
}

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        boolean deleted = deliveryManager.deleteDelivery(
            txtDeliveryId.getText());

    if (deleted) {

    deliveryFileHandler.saveDeliveries(
            deliveryManager.getAllDeliveries());

    int row = tblDeliveries.getSelectedRow();

    if (row >= 0) {
        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel)
                tblDeliveries.getModel();

        model.removeRow(row);
    }

    JOptionPane.showMessageDialog(
            this,
            "Delivery deleted successfully.");

} else {

    JOptionPane.showMessageDialog(
            this,
            "Unable to delete delivery..");
}
    
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
         
    deliveryManager.setDeliveryList(
            deliveryFileHandler.loadDeliveries());

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
            tblDeliveries.getModel();

    model.setRowCount(0);

    for (Delivery delivery :
            deliveryManager.getAllDeliveries()) {

        model.addRow(new Object[]{
            delivery.getDeliveryId(),
            delivery.getOrderId(),
            delivery.getDeliveryPersonName(),
            delivery.getDeliveryPersonPhone(),
            delivery.getVehicleNumber(),
            delivery.getDispatchDate(),
            delivery.getExpectedDeliveryDate(),
            delivery.getActualDeliveryDate(),
            delivery.getDeliveryStatus(),
            delivery.getRemarks()
        });
    

    JOptionPane.showMessageDialog(
            this,
            "Deliveries loaded successfully.");
}

    }//GEN-LAST:event_btnLoadActionPerformed

    private void tblDeliveriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeliveriesMouseClicked
        // TODO add your handling code here:

    int row = tblDeliveries.getSelectedRow();

    if (row >= 0) {

        txtDeliveryId.setText(
                tblDeliveries.getValueAt(row, 0).toString()
        );

        txtOrderId.setText(
                tblDeliveries.getValueAt(row, 1).toString()
        );

        txtPersonName.setText(
                tblDeliveries.getValueAt(row, 2).toString()
        );

        txtPhone.setText(
                tblDeliveries.getValueAt(row, 3).toString()
        );

        txtVehicle.setText(
                tblDeliveries.getValueAt(row, 4).toString()
        );

        txtDispatchDate.setText(
                tblDeliveries.getValueAt(row, 5).toString()
        );

        txtExpectedDate.setText(
                tblDeliveries.getValueAt(row, 6).toString()
        );

        txtActualDate.setText(
                tblDeliveries.getValueAt(row, 7).toString()
        );

        cmbStatus.setSelectedItem(
                tblDeliveries.getValueAt(row, 8).toString()
        );

        txtRemarks.setText(
                tblDeliveries.getValueAt(row, 9).toString()
        );
    }



    }//GEN-LAST:event_tblDeliveriesMouseClicked

    private void txtDispatchDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDispatchDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDispatchDateActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:

    int total = deliveryManager.getAllDeliveries().size();

    int assigned = 0;
    int dispatched = 0;
    int inTransit = 0;
    int delivered = 0;
    int failed = 0;
    int returned = 0;

    for (Delivery delivery : deliveryManager.getAllDeliveries()) {

        if (delivery.getDeliveryStatus() == DeliveryStatus.ASSIGNED) {
            assigned++;

        } else if (delivery.getDeliveryStatus() == DeliveryStatus.DISPATCHED) {
            dispatched++;

        } else if (delivery.getDeliveryStatus() == DeliveryStatus.IN_TRANSIT) {
            inTransit++;

        } else if (delivery.getDeliveryStatus() == DeliveryStatus.DELIVERED) {
            delivered++;

        } else if (delivery.getDeliveryStatus() == DeliveryStatus.FAILED) {
            failed++;

        } else if (delivery.getDeliveryStatus() == DeliveryStatus.RETURNED) {
            returned++;
        }
    }

    lblTotal.setText(String.valueOf(total));
    lblAssigned.setText(String.valueOf(assigned));
    lblDispatched.setText(String.valueOf(dispatched));
    lblInTransit.setText(String.valueOf(inTransit));
    lblDelivered.setText(String.valueOf(delivered));
    lblFailed.setText(String.valueOf(failed));
    lblReturned.setText(String.valueOf(returned));

    }//GEN-LAST:event_btnReportActionPerformed
    private void loadPendingOrders() {

    javax.swing.table.DefaultTableModel model =

            (javax.swing.table.DefaultTableModel) tblPendingOrders.getModel();

    model.setRowCount(0);

    for (Order order : orderManager.getOrders()) {

        if (order.getStatus() == OrderStatus.READY_FOR_DISPATCH
        || order.getStatus() == OrderStatus.PACKED) {

    model.addRow(new Object[]{
        order.getOrderId(),
        order.getCustomerName(),
        order.getDeliveryAddress(),
        order.getStatus()
    });
}

        }


}

    private void btnSelectOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectOrderActionPerformed
        // TODO add your handling code here:

    int row = tblPendingOrders.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this,
                "Please select an order first.");
        return;
    }

    txtOrderId.setText(
            tblPendingOrders.getValueAt(row, 0).toString()
    );

    JOptionPane.showMessageDialog(this,
            "Order selected successfully.");

    }//GEN-LAST:event_btnSelectOrderActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DeliveryManagementGUI().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelectOrder;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSearchType;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblAssigned;
    private javax.swing.JLabel lblDelivered;
    private javax.swing.JLabel lblDispatched;
    private javax.swing.JLabel lblFailed;
    private javax.swing.JLabel lblInTransit;
    private javax.swing.JLabel lblReturned;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblDeliveries;
    private javax.swing.JTable tblPendingOrders;
    private javax.swing.JTextField txtActualDate;
    private javax.swing.JTextField txtDeliveryId;
    private javax.swing.JTextField txtDispatchDate;
    private javax.swing.JTextField txtExpectedDate;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtPersonName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextArea txtRemarks;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtVehicle;
    // End of variables declaration//GEN-END:variables
}